# **Ranking From Scratch:**

## **Perform Ranking:**

In [1]:
# Install necessary libaries:

!pip install sentence_transformers -q
!pip install langchain langchain_community -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.1/227.1 kB 1.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21.3 MB 30.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 975.5/975.5 kB 5.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 27.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 332.8/332.8 kB 20.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.4/127.4 kB 2.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.2/49.2 kB 4.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.0/145.0 kB 10.9 MB/s eta 0:00:00


In [2]:
# Documents:

documents = [
    "This is a list which containing sample documents.",
    "Keywords are important for keyword-based search.",
    "Document analysis involves extracting keywords.",
    "Keyword-based search relies on sparse embeddings.",
    "Understanding document structure aids in keyword extraction.",
    "Efficient keyword extraction enhances search accuracy.",
    "Semantic similarity improves document retrieval performance.",
    "Machine learning algorithms can optimize keyword extraction methods.",
    "Machine learning (ML) is defined as a discipline of artificial intelligence (AI) that provides machines the ability to automatically learn from data and past experiences to identify patterns and make predictions with minimal human intervention.",
    "There are four types of machine learning algorithms: supervised, semi-supervised, unsupervised and reinforcement.",
    "Statistics is a mathematical body of science that pertains to the collection, analysis, interpretation or explanation, and presentation of data, or as a branch of mathematics. ",
    "Descriptive and Inferential Statistics.",
    "Hi, I am Dibyendu Biswas, learning Hybrid-Search, Keyword Search, Vector Search."
]

In [3]:
from sentence_transformers import SentenceTransformer

/usr/local/lib/python3.10/dist-packages/sentence_transformers/cross_encoder/CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange


In [ ]:
# Load pre-trained Sentence Transformer model for creating embeddings:

model_name = 'sentence-transformers/paraphrase-xlm-r-multilingual-v1'
model = SentenceTransformer(model_name)

In [6]:
# Create Embeddigs based on documents:

document_embeddings = model.encode(documents)

In [8]:
document_embeddings[0]

array([ 0.10894687,  0.07812072,  0.11626563, -0.31912503,  0.46890235,
        0.43514383,  0.01453741,  0.44238755,  0.29716393, -0.18982707,
        0.07389057, -0.27864924,  0.21338163, -0.12077013,  0.17891704,
       -0.00789886,  0.04754867, -0.1820457 ,  0.3422711 , -0.0699426 ,
       -0.1428874 ,  0.5714125 , -0.11153242, -0.178954  ,  0.01523124,
        0.2610571 , -0.20555837,  0.05203113, -0.02810759,  0.23873235,
        0.01206979,  0.04404923,  0.02242314, -0.1389518 , -0.7410037 ,
        0.25601006,  0.0814968 ,  0.18820494, -0.4123769 ,  0.11368617,
        0.2812116 ,  0.05860877, -0.17318784,  0.33549133,  0.2180369 ,
       -0.05090719, -0.05457786, -0.8738478 , -0.24082261,  0.3200697 ,
        0.44761658,  0.06347825,  0.5357484 ,  0.16607252, -0.33196995,
        0.33393636,  0.28615916, -0.5419566 , -0.2713242 ,  0.2488116 ,
       -0.23919387, -0.46926287,  0.13836573,  0.37842885, -0.01304426,
        0.01990603,  0.32365084,  0.45857546,  0.07600262,  0.25

In [7]:
# Len of embeddings:

len(document_embeddings[0])

768

In [ ]:
# Create query embeddings:

query = "Natural language processing techniques enhance keyword extraction efficiency."
query_embedding = model.encode(query)
query_embedding

In [10]:
len(query_embedding)

768

In [11]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [12]:
# get the Similarity scores based on query_embeddings:

similarities = cosine_similarity(np.array([query_embedding]), document_embeddings)
similarities

array([[0.16948149, 0.4580228 , 0.5675695 , 0.441233  , 0.6316117 ,
        0.75214124, 0.550352  , 0.74481666, 0.20000125, 0.20946425,
        0.30530158, 0.30916956, 0.23957118]], dtype=float32)

In [13]:
# Get the top most similarity index

most_similar_index = np.argmax(similarities)
most_similar_index

5

In [14]:
# Get the corresponding documents:

documents[most_similar_index]

'Efficient keyword extraction enhances search accuracy.'

In [17]:
# Sorted the indexes based on similarity scores:

sorted_indices = np.argsort(similarities[0])[::-1]


# And then get the Ranked Documents:
ranked_documents = [(documents[i], similarities[0][i]) for i in sorted_indices]
ranked_documents

[('Efficient keyword extraction enhances search accuracy.', 0.75214124),
 ('Machine learning algorithms can optimize keyword extraction methods.',
  0.74481666),
 ('Understanding document structure aids in keyword extraction.', 0.6316117),
 ('Document analysis involves extracting keywords.', 0.5675695),
 ('Semantic similarity improves document retrieval performance.', 0.550352),
 ('Keywords are important for keyword-based search.', 0.4580228),
 ('Keyword-based search relies on sparse embeddings.', 0.441233),
 ('Descriptive and Inferential Statistics.', 0.30916956),
 ('Statistics is a mathematical body of science that pertains to the collection, analysis, interpretation or explanation, and presentation of data, or as a branch of mathematics. ',
  0.30530158),
 ('Hi, I am Dibyendu Biswas, learning Hybrid-Search, Keyword Search, Vector Search.',
  0.23957118),
 ('There are four types of machine learning algorithms: supervised, semi-supervised, unsupervised and reinforcement.',
  0.2094642

In [18]:
print("Ranked Documents:")
for rank, (document, similarity) in enumerate(ranked_documents, start=1):
    print(f"Rank {rank}: Document - '{document}', Similarity Score - {similarity}")

Ranked Documents:
Rank 1: Document - 'Efficient keyword extraction enhances search accuracy.', Similarity Score - 0.7521412372589111
Rank 2: Document - 'Machine learning algorithms can optimize keyword extraction methods.', Similarity Score - 0.7448166608810425
Rank 3: Document - 'Understanding document structure aids in keyword extraction.', Similarity Score - 0.631611704826355
Rank 4: Document - 'Document analysis involves extracting keywords.', Similarity Score - 0.5675694942474365
Rank 5: Document - 'Semantic similarity improves document retrieval performance.', Similarity Score - 0.5503519773483276
Rank 6: Document - 'Keywords are important for keyword-based search.', Similarity Score - 0.458022803068161
Rank 7: Document - 'Keyword-based search relies on sparse embeddings.', Similarity Score - 0.4412330090999603
Rank 8: Document - 'Descriptive and Inferential Statistics.', Similarity Score - 0.30916956067085266
Rank 9: Document - 'Statistics is a mathematical body of science that 

In [20]:
# Print Top 5 Ranked Documents:

print("Ranked Documents:")
for rank, (document, similarity) in enumerate(ranked_documents[:5], start=1):
    print(f"Rank {rank}: Document - '{document}', Similarity Score - {similarity}")

Ranked Documents:
Rank 1: Document - 'Efficient keyword extraction enhances search accuracy.', Similarity Score - 0.7521412372589111
Rank 2: Document - 'Machine learning algorithms can optimize keyword extraction methods.', Similarity Score - 0.7448166608810425
Rank 3: Document - 'Understanding document structure aids in keyword extraction.', Similarity Score - 0.631611704826355
Rank 4: Document - 'Document analysis involves extracting keywords.', Similarity Score - 0.5675694942474365
Rank 5: Document - 'Semantic similarity improves document retrieval performance.', Similarity Score - 0.5503519773483276


## **Perform Re-Ranking:**

### **Using BM25:**

In [21]:
!pip install rank_bm25 -q

In [22]:
from rank_bm25 import BM25Okapi

In [24]:
# Get the Top 4 Documents:

top_4_documents = [doc[0] for doc in ranked_documents[:4]]
top_4_documents

['Efficient keyword extraction enhances search accuracy.',
 'Machine learning algorithms can optimize keyword extraction methods.',
 'Understanding document structure aids in keyword extraction.',
 'Document analysis involves extracting keywords.']

In [26]:
# Tokenized the top_4-documents by splitting:

tokenized_top_4_documents = [doc.split() for doc in top_4_documents]
tokenized_top_4_documents

[['Efficient', 'keyword', 'extraction', 'enhances', 'search', 'accuracy.'],
 ['Machine',
  'learning',
  'algorithms',
  'can',
  'optimize',
  'keyword',
  'extraction',
  'methods.'],
 ['Understanding',
  'document',
  'structure',
  'aids',
  'in',
  'keyword',
  'extraction.'],
 ['Document', 'analysis', 'involves', 'extracting', 'keywords.']]

In [27]:
# Tokenized the query also:

query = "Natural language processing techniques enhance keyword extraction efficiency."
tokenized_query = query.split()
tokenized_query

['Natural',
 'language',
 'processing',
 'techniques',
 'enhance',
 'keyword',
 'extraction',
 'efficiency.']

In [28]:
# Apply BM25 also on tokenized_top_4_documents

bm25 = BM25Okapi(tokenized_top_4_documents)
bm25

In [29]:
# get scores based on tokenized_query:

bm25_scores = bm25.get_scores(tokenized_query)
bm25_scores

array([0.1907998 , 0.16686672, 0.17803252, 0.        ])

In [33]:
# Get the index by soring bm25_scores:

sorted_indices2 = np.argsort(bm25_scores)[::-1]
sorted_indices2

array([0, 2, 1, 3])

In [40]:
# Get the Re-Ranked Documents:

reranked_documents_bm25 = [(top_4_documents[i], bm25_scores[i]) for i in sorted_indices2]
reranked_documents_bm25

[('Efficient keyword extraction enhances search accuracy.',
  0.19079979534096053),
 ('Understanding document structure aids in keyword extraction.',
  0.1780325227902643),
 ('Machine learning algorithms can optimize keyword extraction methods.',
  0.1668667199671815),
 ('Document analysis involves extracting keywords.', 0.0)]

In [41]:
# Print Re-Rankings Documents:

print("Rerank of top 4 Documents:")
for rank, (document, similarity) in enumerate(reranked_documents_bm25, start=1):
    print(f"Rank {rank}: Document - '{document}', Similarity Score - {similarity}")

Rerank of top 4 Documents:
Rank 1: Document - 'Efficient keyword extraction enhances search accuracy.', Similarity Score - 0.19079979534096053
Rank 2: Document - 'Understanding document structure aids in keyword extraction.', Similarity Score - 0.1780325227902643
Rank 3: Document - 'Machine learning algorithms can optimize keyword extraction methods.', Similarity Score - 0.1668667199671815
Rank 4: Document - 'Document analysis involves extracting keywords.', Similarity Score - 0.0


### **Cross Encoder:**

In [39]:
ranked_documents_ = top_4_documents
ranked_documents_

['Efficient keyword extraction enhances search accuracy.',
 'Machine learning algorithms can optimize keyword extraction methods.',
 'Understanding document structure aids in keyword extraction.',
 'Document analysis involves extracting keywords.']

In [42]:
from sentence_transformers import CrossEncoder

In [43]:
# get the model for embeddings:

cross_encoder = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/794 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/316 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [44]:
# Get the Top 4 Ranked Documents:

ranked_documents_ = top_4_documents
ranked_documents_

['Efficient keyword extraction enhances search accuracy.',
 'Machine learning algorithms can optimize keyword extraction methods.',
 'Understanding document structure aids in keyword extraction.',
 'Document analysis involves extracting keywords.']

In [45]:
# Query:

query = "Natural language processing techniques enhance keyword extraction efficiency."

In [46]:
# Create Pairs of query & documents:

pairs = []
for doc in top_4_documents:
    pairs.append([query, doc])
pairs

[['Natural language processing techniques enhance keyword extraction efficiency.',
  'Efficient keyword extraction enhances search accuracy.'],
 ['Natural language processing techniques enhance keyword extraction efficiency.',
  'Machine learning algorithms can optimize keyword extraction methods.'],
 ['Natural language processing techniques enhance keyword extraction efficiency.',
  'Understanding document structure aids in keyword extraction.'],
 ['Natural language processing techniques enhance keyword extraction efficiency.',
  'Document analysis involves extracting keywords.']]

In [47]:
# Get the scores, by applying Cross Encoder:

scores = cross_encoder.predict(pairs)
scores

array([ 3.137871 ,  0.8421656, -2.9193   , -2.8781917], dtype=float32)

In [48]:
scored_docs = zip(scores, top_4_documents)

In [49]:
# Get the Re-Ranked Documents by applying Cross Encoder:

reranked_document_cross_encoder = sorted(scored_docs, reverse=True)
reranked_document_cross_encoder

[(3.137871, 'Efficient keyword extraction enhances search accuracy.'),
 (0.8421656,
  'Machine learning algorithms can optimize keyword extraction methods.'),
 (-2.8781917, 'Document analysis involves extracting keywords.'),
 (-2.9193, 'Understanding document structure aids in keyword extraction.')]

In [53]:
# Compare with BM25:

reranked_documents_bm25

[('Efficient keyword extraction enhances search accuracy.',
  0.19079979534096053),
 ('Understanding document structure aids in keyword extraction.',
  0.1780325227902643),
 ('Machine learning algorithms can optimize keyword extraction methods.',
  0.1668667199671815),
 ('Document analysis involves extracting keywords.', 0.0)]

### **Cohere API:**

In [ ]:
!pip install cohere -q

In [55]:
import cohere

In [56]:
# Initialized Cohere Client:

co = cohere.Client("6oCIsCbqXXXJUBo34Ah6zZh6ZbpKnk0jfqWzWqsq")

In [57]:
# Get the Top 4 Ranked Documents:

ranked_documents_ = top_4_documents
ranked_documents_

['Efficient keyword extraction enhances search accuracy.',
 'Machine learning algorithms can optimize keyword extraction methods.',
 'Understanding document structure aids in keyword extraction.',
 'Document analysis involves extracting keywords.']

In [58]:
query = "Natural language processing techniques enhance keyword extraction efficiency."
query

'Natural language processing techniques enhance keyword extraction efficiency.'

In [59]:
# get the responses based on Cohere API:

response = co.rerank(
    model="rerank-english-v3.0",
    query=query,
    documents=ranked_documents_,
    return_documents=True
)

response

RerankResponse(id='f050e6e5-682a-485e-8e21-280bdf5f5333', results=[RerankResponseResultsItem(document=RerankResponseResultsItemDocument(text='Efficient keyword extraction enhances search accuracy.'), index=0, relevance_score=0.99411184), RerankResponseResultsItem(document=RerankResponseResultsItemDocument(text='Machine learning algorithms can optimize keyword extraction methods.'), index=1, relevance_score=0.9129032), RerankResponseResultsItem(document=RerankResponseResultsItemDocument(text='Understanding document structure aids in keyword extraction.'), index=2, relevance_score=0.32885265), RerankResponseResultsItem(document=RerankResponseResultsItemDocument(text='Document analysis involves extracting keywords.'), index=3, relevance_score=0.02865267)], meta=ApiMeta(api_version=ApiMetaApiVersion(version='1', is_deprecated=None, is_experimental=None), billed_units=ApiMetaBilledUnits(input_tokens=None, output_tokens=None, search_units=1, classifications=None), tokens=None, warnings=None)

In [60]:
response.results[0].document.text

'Efficient keyword extraction enhances search accuracy.'

In [61]:
response.results[0].relevance_score

0.99411184

In [63]:
# Get Re-ranked results:

reranked_document_cohere_api = [ (response.results[i].document.text, response.results[i].relevance_score) for i in range(4)]
reranked_document_cohere_api

[('Efficient keyword extraction enhances search accuracy.', 0.99411184),
 ('Machine learning algorithms can optimize keyword extraction methods.',
  0.9129032),
 ('Understanding document structure aids in keyword extraction.', 0.32885265),
 ('Document analysis involves extracting keywords.', 0.02865267)]